
class Client {
    id
    prenom
    nom
    telephone
    mail
}

class Vente {
    id 
    montantTotal 
    date
    status
    
}

class PaiementMode{
    id
    nomMode
}

class LigneVente{
    id
    quantiteVente
    prixVente
}

class Produit{
    id
    libelle
    prixUnitaire
    qteStock
}

Client "1" -- "0..*"Vente
LigneVente "0..*" --"1"Vente
PaiementMode "1" -- "0..*"Vente
LigneVente "0..*"-- "1"Produit