@startuml usecase
left to right direction
actor "utilisateur" as u

rectangle "gestion produit"{
    usecase "enregistrer vente" as EV
    usecase "enregistrer client" as EC
    usecase "enregistrer produit" as EP
    usecase "lister commandes" as LC
    usecase "annuler commande" as AC
    usecase "livrer commande" as LivC
    usecase "lister produit" as LS
    usecase "selectionner client" as SC
    usecase "Ajouter articles dans vente" as AV
    usecase "lister Produits avec stock critique" as LPS
    usecase "afficher statistiques" as ASC
    usecase "ventes validees" as VV
    usecase "nombre de commandes" as TC
    usecase " nombre de commandes en attente" as TCA
    usecase " nombre de produits en alerte stock" as TCAS
}

u->EV
u->EC
u->EP
u->LC
u->LPS
u->ASC
ASC ..> VV: <<include>>
ASC ..> TCA: <<include>>
ASC ..> TC: <<include>>
ASC ..> TCAS: <<include>>
LC<..LivC : <<extend>>
LC<..AC : <<extend>>
LC<..LS : <<extend>>
EV ..>SC: <<include>>
EV ..>AV: <<include>>



@enduml