@startuml dashboard
left to right direction
actor "Admin" as A

rectangle "dashboard" {
    usecase "Se connecter" as sc
    usecase "lister stats partiel" as lsp
    usecase "lister stats agregat" as lsa
}


A-> lsp
A-> lsa

lsp ..> sc:<<include>>
lsa ..> sc:<<include>>



@enduml