@startuml approvisionnement

top to bottom direction

actor "Admin" as A
actor "Charge Stock" as CS

rectangle "Gestion Appro"{
    usecase "lister appro"  as lp
    usecase "calculer stats" as cs

    usecase "lister ligne appro" as la
    usecase "receptionner appro" as r

    usecase "lister produit" as lpd
    usecase "valider appro" as va

    usecase "Se connecter" as sc
}

A ..|> CS

CS -> lp
CS -> cs

lp <.. r:<<extend>>
lp <.. la:<<extend>>

lp ..> sc:<<include>>
cs ..> sc:<<include>>

r ..> lpd:<<include>>
r ..> va:<<include>>

@enduml